=== akurilov/mongoose/scenario/scenario-schema.json
{
	"$schema" : "http://json-schema.org/draft-04/schema#",
	"id" : "scenario-schema.json",
	"type" : "object",
	"additionalProperties" : false,
	"properties" : {
		"type" : {
			"type" : "string",
			"enum" : [
				"command",
				"for",
				"load",
				"parallel",
				"precondition",
				"sequential"
			]
		},
		"jobs" : {
			"type" : "array",
			"items" : {
				"type" : "object",
				"$ref" : "scenario-schema.json"
			}
		},
		"value" : {
			"oneOf" : [
				{
					"type" : "string"
				}, {
					"type" : "integer"
				}
			]
		},
		"blocking" : {
			"type" : "boolean"
		},
		"in" : {
			"type" : "array"
		},
		"config" : {
			"type": "object",
			"additionalProperties" : false,
			"properties": {
				"auth": {
					"type": "object",
					"properties": {
						"id": {
							"type": [
								"null",
								"string"
							]
						},
						"secret": {
							"type": [
								"null",
								"string"
							]
						},
						"token": {
							"type": [
								"null",
								"string"
							]
						}
					}
				},
				"io": {
					"type": "object",
					"additionalProperties" : false,
					"properties": {
						"buffer": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"size": {
									"type": "object",
									"additionalProperties" : false,
									"properties": {
										"min": {
											"oneOf" : [
												{
													"type": "integer",
													"minimum" : 1
												}, {
													"type" : "string",
													"pattern" : "[\\d\\.]+[KMGTPE]?B?"
												}, {
													"type" : "string",
													"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
												}
											]
										},
										"max": {
											"oneOf" : [
												{
													"type": "integer",
													"minimum" : 1
												}, {
													"type" : "string",
													"pattern" : "[\\d\\.]+[KMGTPE]?B?"
												}, {
													"type" : "string",
													"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
												}
											]
										}
									}
								}
							}
						}
					}
				},
				"item": {
					"type": "object",
					"additionalProperties" : false,
					"properties": {
						"type": {
							"oneOf" : [
								{
									"type" : "string",
									"enum" : [
										"container",
										"data",
										"token"
									]
								}, {
									"type" : "string",
									"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
								}
							]
						},
						"data": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"content": {
									"type": "object",
									"additionalProperties" : false,
									"properties": {
										"file": {
											"type": [
												"null",
												"string"
											]
										},
										"seed": {
											"oneOf" : [
												{
													"type": "string",
													"pattern" : "\\w+"
												}, {
													"type" : "string",
													"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
												}
											]
										},
										"ringSize": {
											"oneOf" : [
												{
													"type": "integer",
													"minimum" : 1
												}, {
													"type" : "string",
													"pattern" : "[\\d\\.]+[KMGTPE]?B?"
												}, {
													"type" : "string",
													"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
												}
											]
										}
									}
								},
								"ranges": {
									"oneOf": [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d]+\\-[\\d]+"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"size": {
									"oneOf" : [
										{
											"type": "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d\\.]+[KMGTPE]?B?"
										}, {
											"type" : "string",
											"pattern" : "\\.*(\\$\\{[\\w\\-_]+\\})+\\.*"
										}
									]
								},
								"verify": {
									"type": "boolean"
								}
							}
						},
						"dst": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"container": {
									"type": [
										"null",
										"string"
									]
								},
								"file": {
									"type": [
										"null",
										"string"
									]
								}
							}
						},
						"src": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"container": {
									"type": [
										"null",
										"string"
									]
								},
								"file": {
									"oneOf" : [
										{
											"type" : "null"
										}, {
											"type" : "string"
										}, {
											"type" : "array",
											"items" : {
												"oneOf" : [
													{
														"type" : "null"
													}, {
														"type" : "string"
													}
												]
											}
										}
									]
								},
								"batchSize": {
									"type": "integer",
									"minimum" : 1
								}
							}
						},
						"naming": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"type": {
									"oneOf" : [
										{
											"type": "string",
											"enum" : [
												"asc",
												"desc",
												"random"
											]
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"prefix": {
									"type": [
										"null",
										"string"
									]
								},
								"radix": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 2,
											"maximum" : 36
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"offset": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"length": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 1
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								}
							}
						},
						"queue": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"sizeLimit": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								}
							}
						}
					}
				},
				"load": {
					"type": "object",
					"additionalProperties" : false,
					"properties": {
						"circular": {
							"oneOf" : [
								{
									"type": "boolean"
								}, {
									"type" : "string",
									"pattern" : "[a-zA-Z]*(\\$\\{[\\w\\-_]+\\})+[a-zA-Z]*"
								}
							]
						},
						"type": {
							"oneOf" : [
								{
									"type" : "string",
									"enum" : [
										"create",
										"read",
										"update",
										"delete"
									]
								}, {
									"type" : "string",
									"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
								}, {
									"type" : "array",
									"items" : {
										"oneOf" : [
											{
												"type" : "string",
												"pattern" : "[CcRrEeAaTtDdUuPpLl]+=?[\\d]?%?"
											}, {
												"type" : "string",
												"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
											}
										]
									}
								}
							]
						},
						"threads": {
							"oneOf" : [
								{
									"type" : "integer",
									"minimum" : 1
								}, {
									"type" : "string",
									"pattern" : "\\d*(\\$\\{[\\w\\-_]+\\})+\\d*"
								}
							]
						},
						"limit": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"count": {
									"oneOf" : [
										{
											"type": "integer"
										}, {
											"type" : "string",
											"pattern" : "\\d*(\\$\\{[\\w\\-_]+\\})+\\d*"
										}
									]
								},
								"rate": {
									"oneOf" : [
										{
											"type": "number",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"size": {
									"oneOf" : [
										{
											"type": "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d\\.]+[KMGTPE]?B?\\-?[\\d\\.]?[KMGTPE]?B?"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"time": {
									"type": "string"
								}
							}
						},
						"metrics" : {
							"type" : "object",
							"additionalProperties" : false,
							"properties" : {
								"intermediate" : {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"period" : {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : "[\\d]+[SsMmHhDd]?"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"precondition" : {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								}
							}
						},
						"server": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"addrs": {
									"type": "array",
									"items": {
										"type": "string"
									}
								},
								"nodeMapping": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								}
							}
						}
					}
				},
				"network": {
					"type": "object",
					"additionalProperties" : false,
					"properties": {
						"serveJMX": {
							"oneOf" : [
								{
									"type": "boolean"
								}, {
									"type" : "string",
									"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
								}
							]
						},
						"socket": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"timeoutMilliSec": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"reuseAddr": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"keepAlive": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"tcpNoDelay": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"linger": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"bindBacklogSize": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"interestOpQueued": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"selectInterval": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								}
							}
						},
						"ssl" : {
							"oneOf" : [
								{
									"type": "boolean"
								}, {
									"type" : "string",
									"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
								}
							]
						}
					}
				},
				"run": {
					"type": "object",
					"additionalProperties" : false,
					"properties": {
						"id": {
							"type": [
								"null",
								"string"
							]
						},
						"file": {
							"type": [
								"null",
								"string"
							]
						},
						"mode": {
							"oneOf" : [
								{
									"type" : "string",
									"enum" : [
										"standalone",
										"client",
										"server",
										"wsmock",
										"webui"
									]
								}, {
									"type" : "string",
									"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
								}
							]
						},
						"name": {
							"type": "string"
						},
						"resume": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"enabled": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								}
							}
						},
						"version": {
							"type": "string"
						}
					}
				},
				"storage": {
					"type": "object",
					"additionalProperties" : false,
					"properties": {
						"type": {
							"oneOf" : [
								{
									"type" : "string",
									"enum" : [
										"fs",
										"http"
									]
								}, {
									"type" : "string",
									"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
								}
							]
						},
						"addrs": {
							"type": "array",
							"items": {
								"type": "string"
							}
						},
						"port": {
							"oneOf" : [
								{
									"type" : "integer",
									"minimum" : 1
								}, {
									"type" : "string",
									"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
								}
							]
						},
						"http": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"api": {
									"oneOf" : [
										{
											"type" : "string",
											"pattern" : "[\\w\\d]+"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"fsAccess": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"headers": {
									"type": "object",
									"properties": {
									}
								},
								"namespace": {
									"type": [
										"null",
										"string"
									]
								},
								"versioning": {
									"oneOf" : [
										{
											"type": "boolean"
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								}
							}
						},
						"mock": {
							"type": "object",
							"additionalProperties" : false,
							"properties": {
								"headCount": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 1
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"capacity": {
									"oneOf" : [
										{
											"type" : "integer",
											"minimum" : 0
										}, {
											"type" : "string",
											"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
										}
									]
								},
								"container": {
									"type": "object",
									"additionalProperties" : false,
									"properties": {
										"capacity": {
											"oneOf" : [
												{
													"type" : "integer",
													"minimum" : 0
												}, {
													"type" : "string",
													"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
												}
											]
										},
										"countLimit": {
											"oneOf" : [
												{
													"type" : "integer",
													"minimum" : 0
												}, {
													"type" : "string",
													"pattern" : ".*(\\$\\{[\\w\\-_]+\\})+.*"
												}
											]
										}
									}
								}
							}
						}
					}
				}
			}
		}
	},
	"required" : [
		"type"
	]
}

=== akurilov/mongoose/scenario/misc/foreach.json
{
	"type" : "for",
	"value" : "size",
	"in" : [
		0, "1KB", "1MB"
	],
	"config" : {
		"item" : {
			"data" : {
				"size" : "${size}"
			}
		},
		"load" : {
			"limit" : {
				"count" : 1000000,
				"time" : "10s"
			},
			"metrics" : {
				"period" : 0
			}
		}
	},
	"jobs" : [
		{
			"type" : "for",
			"value" : "threads",
			"in" : [
				1, 10, 100
			],
			"config" : {
				"item" : {
					"dst" : {
						"container" : "${size}_${threads}threads"
					}
				},
				"load" : {
					"threads" : "${threads}"
				}
			},
			"jobs" : [
				{
					"type" : "load",
					"config" : {
						"item" : {
							"dst" : {
								"file" : "${size}_${threads}threads.csv"
							}
						},
						"load" : {
							"type" : "create"
						}
					}
				}, {
					"type" : "load",
					"config" : {
						"item" : {
							"src" : {
								"file" : "${size}_${threads}threads.csv"
							}
						},
						"load" : {
							"type" : "read"
						}
					}
				}, {
					"type" : "load",
					"config" : {
						"item" : {
							"src" : {
								"file" : "${size}_${threads}threads.csv"
							}
						},
						"load" : {
							"type" : "delete"
						}
					}
				}
			]
		}
	]
}
